name: tekartik_firebase_firestore_browser
description: Firebase firestore browser
version: 0.6.0
publish_to: none

environment:
  sdk: '>=2.5.0-dev <3.0.0'

dependencies:
  tekartik_firebase_firestore:
    git:
      url: git://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: dart2
    version: '>=0.5.0'
  tekartik_firebase_browser:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_browser
      ref: dart2
    version: '>=0.6.0'
  firebase: '>=7.0.0'
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: dart2
    version: '>=0.6.8+2'

dev_dependencies:
  test: ">=0.12.37"
  dev_test: '>=0.12.0-dev.1'
  http: any
  yaml: any
  build_runner: ">=0.9.1"
  build_test: ">=0.10.3"
  build_web_compilers: ">=0.4.0+4"
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.3.4'
  process_run: '>=0.10.2'

dependency_overrides:
  tekartik_firebase_firestore:
    path: ../firestore
  tekartik_firebase_firestore_test:
    path: ../firestore_test
#  firebase:
#    path: ../../../tekartik-2/firebase-dart