name: tekartik_firebase_firestore_idb
description: Firebase firestore browser
version: 0.4.2
publish_to: none

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  tekartik_firebase_firestore:
    git:
      url: git://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: dart2
    version: '>=0.4.2'
  tekartik_firebase_local:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_local
      ref: dart2
    version: '>=0.3.7'
  idb_shim: '>=1.7.0+1'
  uuid:
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: dart2

dev_dependencies:
  test: ">=0.12.37"
  dev_test: '>=0.12.0-dev.1'
  http: any
  yaml: any
  build_runner: ">=0.9.1"
  build_test: ">=0.10.3"
  build_web_compilers: ">=0.4.0+4"
  process_run: '>=0.10.2'

dependency_overrides:
  tekartik_firebase_firestore:
    path: ../firestore
  tekartik_firebase_firestore_test:
    path: ../firestore_test