name: tekartik_firebase_firestore
description: Firebase firestore core
version: 0.5.3
author: alex <alex@tekartik.com>
publish_to: none

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  meta:
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2
    version: '>=0.3.7'
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.10.7'

dev_dependencies:
  test: "^1.0.0"
  process_run: '>=0.10.2'
