name: tekartik_firebase_firestore_sim_browser
description: Firebase simulation browser client
version: 0.7.0
publish_to: none

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  tekartik_firebase_sim_browser:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_sim_browser
      ref: dart2
    version: '>=0.3.7'
  tekartik_firebase_firestore_sim:
    git:
      url: git://github.com/tekartik/firebase_firestore.dart
      path: firestore_sim
      ref: dart2
    version: '>=0.8.0'

dev_dependencies:
  test: ">=0.12.37"
  dev_test: '>=0.12.0-dev.1'
  build_runner: ">=0.9.1"
  build_web_compilers: ">=0.4.0+4"
  process_run: '>=0.10.2'

dependency_overrides:
  tekartik_firebase_firestore_test:
    path: ../firestore_test
  tekartik_firebase_firestore_sim:
    path: ../firestore_sim
  tekartik_firebase_firestore:
    path: ../firestore